---
# journald: entry point for tasks
#                 Generally only include other file(s) and add tags here.

- name: Include JournalD tasks
  ansible.builtin.include_tasks: journald.yml
  tags: journald
