---
exclude: |
  (?x)^(
      Gemfile\.lock|
      playbooks/.*/inventory|
      playbooks/.*/roles|
      vendor/bundle/.*|
      tmp/.*|
      \.kitchen/.*|
      screenlog\..*|
      .*\.retry|
      \.mypy_cache/.*|
      CHANGELOG\.rst
  )$
repos:
  - repo: https://github.com/ansible-network/collection_prep
    rev: 1.1.1
    hooks:
      # - id: autoversion # removed as being handled by GHA push and release drafter
      - id: update-docs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            .*\.patch|
            .*/README\.md|
            .*/LICENSE
          )$
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            .*\.patch|
            .*/README\.md|
            .*/LICENSE
          )$

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

#  - repo: https://github.com/pycontribs/mirrors-prettier
#    rev: "v3.4.2"
#    hooks:
#      - id: prettier
#        entry: env CI=1 bash -c "prettier --list-different . || ec=$? && prettier --loglevel=error --write . && exit $ec"
#        pass_filenames: false
#        args: []
#        additional_dependencies:
#          - prettier
#          - prettier-plugin-toml
#        exclude: |
#          (?x)^(
#            .*\.patch|
#            .*/LICENSE|
#            \.mypy_cache/.*|
#            CHANGELOG\.rst|
#            \.kitchen\.?.*\.yml
#          )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
        alias: ruff
        args:
          - "--fix"
          - "--show-fixes"
      - id: ruff-format
        alias: ruff
