---
# openwrt_base: entry point for tasks
#               Generally only include other file(s) and add tags here.

- name: "Run tasks: bootstrap-ip"
  ansible.builtin.import_tasks: bootstrap-ip.yml
  tags:
    - bootstrap_ip
    - openwrt_bootstrap
    - ansible_bootstrap
    - bootstrap
- name: "Run tasks: python-openwrt"
  ansible.builtin.import_tasks: python-openwrt.yml
  tags:
    - python-openwrt
    - openwrt_bootstrap
    - ansible_bootstrap
    - bootstrap
- name: "Run tasks: setup-openwrt-release-facts"
  ansible.builtin.import_tasks: setup-openwrt-release-facts.yml
  tags:
    - opkg-openwrt
    - apk-openwrt
    - openwrt_base-facts
    - openwrt-setup-openwrt-release-facts
- name: "Run tasks: opkg-openwrt"
  ansible.builtin.import_tasks: opkg-openwrt.yml
  tags: opkg-openwrt
- name: "Run tasks: apk-openwrt"
  ansible.builtin.import_tasks: apk-openwrt.yml
  tags: apk-openwrt
- name: "Run tasks: logrotate"
  ansible.builtin.import_tasks: logrotate.yml
  tags: logrotate-openwrt
- name: "Run tasks: crontabs"
  ansible.builtin.import_tasks: crontabs.yml
  tags:
    - crontabs-openwrt
    - openwrt_base-crontabs
- name: "Run tasks: kernel (sysctl.d)"
  ansible.builtin.import_tasks: kernel.yml
  tags:
    - kernel-openwrt
    - sysctl-openwrt
    - openwrt_base-kernel
    - openwrt_base-sysctl
