---
# openwrt_base: Tasks entry point. Called by main.yml

# Placeholder for handling OS-specific vars
# Load a variable file based on the OS type, or a default if not found.
# - name: Include vars
#   ansible.builtin.include_vars: "{{ item }}"
#   with_first_found:
#     - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
#     - "../vars/{{ ansible_distribution }}.yml"
#     - "../vars/{{ ansible_os_family }}.yml"
#     - "../vars/default.yml"
#   when: openwrt_base_logrotate_files is not defined

- name: Install wireless config
  ansible.builtin.template:
    src: templates/etc-config/wireless.j2
    dest: /etc/config/wireless
    owner: root
    group: root
    mode: "0644"
  register: openwrt_wireless
  notify:
    - Reload wifi
