# openwrt_dumbap_base: entry point for defaults
# default.yml - default vars for unsupported / unknown OS
# (Assumes this is OpenWRT LEDE Image)
---
openwrt_dumbap_opkg_packages:
  - arp-scan

openwrt_dumbap_logrotate_files:
  - ddns

openwrt_dumbap_base_wireless:
  "5GHz":
    ssid: OpenWRT_5Ghz
  "2.4GHz":
    ssid: OpenWRT
