---
# tasks file for lyraphase.opnsense-users
- name: Import bootstrap tasks
  ansible.builtin.import_tasks: "bootstrap.yml"
  tags:
    - bootstrap
    - ansible_group
    - users
    - install_users
