---
# openwrt_dumbap_base: entry point for meta
galaxy_info:
  namespace: lyraphase
  author: James Cuzella
  description: A base role to setup OpenWRT as a dumb Wifi Access Point on OpenWRT / LEDE
  company: LyraPhase
  license: AGPL-3.0-or-later
  min_ansible_version: "2.5"
  platforms:
    - name: OpenWrt
      versions:
        - "17.01"
  galaxy_tags:
    - system
    - networking
    - packaging
    - openwrt
  # dependencies:
  # Specify role dependencies here
  # For foo
  #  - foo
# version: 0.0.1 ## Ansible 2.0 broke this. Uncomment if / when they ever fix ansible/ansible#13496
