---
# openwrt_dumbap_base: Tasks entry point. Called by main.yml

# Load a variable file based on the OS type, or a default if not found.
# - include_vars: "{{ item }}"
#  with_first_found:
#    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
#    - "../vars/{{ ansible_distribution }}.yml"
#    - "../vars/{{ ansible_os_family }}.yml"
#    - "../vars/default.yml"
#  when: openwrt_opkg_repo_files is not defined

- name: Setup root crontab
  ansible.builtin.copy:
    src: files/crontabs/root
    dest: /etc/crontabs/root
    owner: root
    group: root
    mode: "0644"
